ptgli/glimanagers/urls.py
from django.urls import path

from . import views

app_name = 'glimanagers'

urlpatterns = [
    path('', views.GLIManagerListView.as_view(), name='list'),
    path('add/', views.GLIManagerAddView.as_view(), name='add'),
    path('<int:pk>/update/', views.GLIManagerUpdateView.as_view(), name='update'),
    path('update/success', views.GLIManagerUpdateSuccessView.as_view(), name='success'),
    path('<int:pk>/', views.GLIManagerDetailsView.as_view(), name='details'),
    path('delete/', views.GLIManagerDeleteView.as_view(), name='delete'),
]

ptgli/ptgli/urls.py
from django.contrib import admin
from django.urls import path, include

# Media (dev)
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/administradores')),
    path('administradores/', include('glimanagers.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ptgli/glimanagers/models.py
from django.db import models

import uuid
from PIL import Image
from io import BytesIO
from django.core.files import File
from django.core.files.base import ContentFile

class GLIManager(models.Model):
    AREA = [
        ('a001', 'Recursos Humanos'),
        ('a002', 'Área 2'),
        ('a003', 'Área 3'),
        ('a004', 'Área 4'),
    ]
    STATUS = [
        (1, 'Activo'),
        (0, 'Inactivo'),
    ]
    display = models.ImageField(upload_to='glimanagers/', null=True, blank=True)
    first_name = models.CharField(max_length=150, default='')
    last_name = models.CharField(max_length=150, default='')
    email = models.EmailField(max_length=150, default='')
    area = models.CharField(max_length=4, choices=AREA, default=AREA[0])
    status = models.IntegerField(choices=STATUS, default=0)

    def save(self, *args, **kwargs):
        if self.pk is None and self.display:
            im = Image.open(self.display)
            source_image = im.convert('RGB')
            source_image.thumbnail((600, 600*im.size[1]/im.size[0]))
            output = BytesIO()
            source_image.save(output, format='JPEG')
            output.seek(0)
            content_file = ContentFile(output.read())
            file = File(content_file)
            random_name = f'{uuid.uuid4()}.jpeg'
            self.display.save(random_name, file, save=False)
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.display.delete()
        return super().delete(*args, **kwargs)

ptgli/glimanagers/forms.py
import django.forms as forms

from .models import GLIManager

class GLIManagerForm(forms.ModelForm):
    """Form definition for GLIManager."""

    class Meta:
        """Meta definition for GLIManagerform."""
        model = GLIManager
        fields = ('display', 'first_name', 'last_name', 'email', 'area', 'status')

    def __init__(self, *args, **kwargs):
        super(GLIManagerForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

ptgli/glimanagers/views.py
from django.db.models import Q

from django.views.generic import View, TemplateView

from django.shortcuts import render, resolve_url, redirect, get_object_or_404

from django.core.paginator import Paginator

from .models import GLIManager

from .forms import GLIManagerForm


class GLIManagerListView(View):
    def get(self, request):

        # Filtrando por buscador
        search_filter = request.GET.get('search')

        # Filtrando por area
        area_filter = request.GET.get('area')
        if area_filter not in list(zip(*GLIManager.AREA))[0]:
            area_filter = None
           
        
        # Filtrando por estado
        try:
            status_filter = request.GET.get('status')
            if status_filter is not None:
                status_filter = int(status_filter)
                if status_filter not in list(zip(*GLIManager.STATUS))[0]:
                    status_filter = None
        except ValueError:
            status_filter = None
        

        # Resultados por pagina
        rows = request.GET.get('rows') or 5
        try:
            rows = int(rows)
        except ValueError:
            rows = 5
        except TypeError:
            rows = 5


        managers = GLIManager.objects.all()
        managers = managers.filter(Q(first_name__icontains=str(search_filter)) | Q(last_name__icontains=str(search_filter))) if search_filter is not None else managers
        if area_filter is not None: managers = managers.filter(area=area_filter)
        if status_filter is not None: managers = managers.filter(status=status_filter)

        managers = managers.order_by('-pk')
        paginator = Paginator(managers, rows)
        page_number = request.GET.get('page') or 1
        page_managers = paginator.get_page(page_number)
        
        search_filter = "" if search_filter is None else str(search_filter)
        area_filter = "" if area_filter is None else str(area_filter)
        status_filter = "" if status_filter is None else status_filter

        return render(request, 'glimanagers/list.html', 
                    context={
                        'page_managers': page_managers,
                        'nrows': rows,
                        'niof': (int(page_number)-1)*rows+1,
                        'nfof': (int(page_number)-1)*rows+len(page_managers),
                        'areaopt': GLIManager.AREA,
                        'statusopt': GLIManager.STATUS,
                        'search_filter': search_filter,
                        'area_filter': area_filter,
                        'status_filter': status_filter,
                    })

class GLIManagerAddView(View):
    def get(self, request):
        form = GLIManagerForm()
        return render(request, 'glimanagers/create.html', context={'form':form})

    def post(self, request):
        form = GLIManagerForm(request.POST, files=request.FILES)
        if (form.is_valid()):
            glimanager = form.save()
            return redirect(resolve_url('glimanagers:list'))
        else:
            return render(request, 'glimanagers/create.html', context={'form':form})


class GLIManagerDetailsView(View):
    def get(self, request, pk):
        glimanager = get_object_or_404(GLIManager, pk=pk)
        return render(request, 'glimanagers/details.html', context={'manager':glimanager})


class GLIManagerUpdateView(View):
    def get(self, request, pk):
        glimanager = get_object_or_404(GLIManager, pk=pk)
        form = GLIManagerForm(instance=glimanager)
        return render(request, 'glimanagers/update.html', context={'form':form, 'manager':glimanager})

    def post(self, request, pk):
        glimanager = get_object_or_404(GLIManager, pk=pk)
        form = GLIManagerForm(request.POST, files=request.FILES, instance=glimanager)
        if (form.is_valid()):
            glimanager = form.save()
            return redirect(resolve_url('glimanagers:success'))
        else:
            return render(request, 'glimanagers/update.html', context={'form':form, 'manager':glimanager})

class GLIManagerUpdateSuccessView(TemplateView):
    template_name = 'glimanagers/success.html'


class GLIManagerDeleteView(View):
    def post(self, request):
        glimanager = get_object_or_404(GLIManager, pk=request.POST.get('pk'))
        glimanager.delete()
        return redirect(resolve_url('glimanagers:list'))

ptgli/glimanagers/templates/glimanagers/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Roboto:ital,wght@0,100;0,400;0,700;0,900;1,100;1,400;1,500;1,700;1,900&family=Mulish:wght@700&display=swap" rel="stylesheet"> 

    <link type="text/css" rel="stylesheet" href="{% static 'glimanagers/glistyles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="gli-sidenav">
        <div class="gli-logo valign-wrapper">
            <img src="{% static 'glimanagers/img/GLI_LogoColor.png' %}" alt="">
        </div>
        <div class="gli-tabs">
            <a class="gli-tab-item gli-active" href="{% url 'glimanagers:list' %}"><img src="{% static 'glimanagers/img/Vector.png' %}"> Administradores</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-1.png' %}"> Catálogos</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-2.png' %}"> Líderes</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-3.png' %}"> Usuarios</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-4.png' %}"> Mi empresa</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-5.png' %}"> Cursos</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-6.png' %}"> Recompensas</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-7.png' %}"> Eventos</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-8.png' %}"> Notificaciones</a>
            <a class="gli-tab-item" href="#"><img src="{% static 'glimanagers/img/Vector-9.png' %}"> Reportes</a>
        </div>
        <div class="gli-footer">
            <div class="valign-wrapper gli-help">
                <div>
                    <span>¿Necesitas ayuda?</span><br>
                    <a href="#">Ir a sección ayuda</a>
                </div>
                <div>
                    <a href="#"><img src="{% static 'glimanagers/img/external-link.png' %}" alt=""></a>
                </div>
            </div>
            <div class="gli-hsep" style="margin-top: 16px; margin-bottom: 16px;"></div>
            <div class="center">
                © Copyright GLI 2021
            </div>
        </div>
    </div>
    <div class="gli-nav valign-wrapper">
        <div>
            <a href="#" class="white-text"><i class="material-icons">search</i></a>
        </div>
        <div class="gli-navsep"></div>
        <div class="valign-wrapper gli-user" style="height: 100%;">
            <div class="valign-wrapper gli-circle-img">
                <img src="{% static 'glimanagers/img/Procter-Gamble-SWOT1.png' %}">
            </div>
            <div class="gli-username">
                <h6>Adrian Stefan<br>Recursos Humanos</h6>
            </div>
            <div>
                <a href="#" class="white-text"><i class="material-icons">logout</i></a>
            </div>
        </div>
    </div>
            
    <div class="gli-tab-container">
        {% block tabcontent %}{% endblock tabcontent %}
    </div>

    
    {% block modal %}{% endblock modal %}
        
    {% block scripts %}{% endblock scripts %}        
</body>
</html>

ptgli/glimanagers/templates/glimanagers/create.html
{% extends 'glimanagers/base.html' %}
{% load static %}
{% block tabcontent %}

<header class="gli-header">
    <div class="gli-breadcrumbs valign-wrapper">
        <a href="#" class="gli-breadcrumb">Inicio</a> <i class="gli-breadcrumb-active material-icons">keyboard_arrow_right</i> <span class="gli-breadcrumb-active">Administradores</span>
    </div>
    <h1 class="head">Agregar administrador</h1>
</header>
<p class="gli-normal-text" style="margin: 24px 0 16px 0;">Sube tu fotografía con un peso menor a 2MB</p>
<div class="add-form">
    <form id="addform" method="POST" enctype="multipart/form-data" style="width: 360px; margin-bottom: 40px;">
        {% csrf_token %}
        <div class="gli-img-dropable">
            <div class="gli-img-dropable-preview gli-img-dropable-no-preview">
                <img src="{% static 'glimanagers/img/nodisplay.png' %}" alt="">
            </div>
            <div class="gli-img-dropable-input">
                <small>Arrastra tu archivo o</small>
                <div class="gli-img-dropable-button-select">
                    {{ form.display }}
                    <label for="{{form.display.id_for_label}}" class="gli-button gli-button-white">Selecciona</label>
                </div>
            </div>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Nombre (s) </legend>
                {{ form.first_name }}
            </fieldset>
            <small class="gli-form-error">{{ form.first_name.errors }}</small>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Apeliidos </legend>
                {{ form.last_name }}
            </fieldset>
            <small class="gli-form-error">{{ form.last_name.errors }}</small>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Correo electrónico </legend>
                {{ form.email }}
            </fieldset>
            <small class="gli-form-error">{{ form.email.errors }}</small>
        </div>
        <div class="gli-input gli-input-select">
            <fieldset>
                <legend>Área</legend>
                {{ form.area }}
            </fieldset>
        </div>
        <div class="gli-input gli-input-select">
            <fieldset>
                <legend>Estatus</legend>
                {{ form.status }}
            </fieldset>
        </div>
    </form>
</div>

<div class="gli-hsep" style="margin-bottom: 16px;"></div>
<div>
    <a class="gli-button gli-button-white" href="{% url 'glimanagers:list' %}">Cancelar</a>
    <button id="addbutton" class="gli-button gli-button-secondary">Agregar administrador</button>
</div>
{% endblock tabcontent %}
{% block scripts %}
<script src="{% static 'glimanagers/glimanagerform.js' %}"></script>
{% endblock scripts %}
    

ptgli/glimanagers/templates/glimanagers/details.html
{% extends 'glimanagers/base.html' %}
{% load static %}
{% load custom_tags %}
{% block tabcontent %}

<header class="gli-header">
    <div class="gli-breadcrumbs valign-wrapper">
        <a href="#" class="gli-breadcrumb">Inicio</a> <i class="gli-breadcrumb-active material-icons">keyboard_arrow_right</i> <span class="gli-breadcrumb-active">Administradores</span>
    </div>
    <h1 class="head">Perfil de administrador</h1>
</header>



{% if manager.display %}
<div class="gli-details-display">
    <img src="{% get_media_prefix %}{{ manager.display }}">
</div>
{% endif %}
    
<h1 class="gli-details-name">{{ manager.first_name }} {{ manager.last_name }}</h2>

<div class="gli-details-data-row">
    <div class="gli-details-data">
        <h5 class="gli-details-data-title">Nombre (s)</h5>
        <h3 class="gli-details-data-value">{{ manager.first_name }}</h3>
    </div>
    <div class="gli-details-data">
        <h5 class="gli-details-data-title">Apellidos</h5>
        <h3 class="gli-details-data-value">{{ manager.last_name }}</h3>
    </div>
    <div class="gli-details-data">
        <h5 class="gli-details-data-title">Correo electrónico</h5>
        <h3 class="gli-details-data-value">{{ manager.email|safe_email }}</h3>
    </div>
</div>
<div class="gli-details-data-row">
    <div class="gli-details-data">
        <h5 class="gli-details-data-title">Área</h5>
        <h3 class="gli-details-data-value">{{ manager.get_area_display }}</h3>
    </div>
    <div class="gli-details-data">
        <h5 class="gli-details-data-title">Estatus</h5>
        <h3 class="gli-details-data-value">{{ manager.get_status_display }}</h3>
    </div>
</div>

<div class="gli-hsep" style="margin-top: 40px; margin-bottom: 16px; width: 100%;"></div>

<a class="gli-button gli-button-secondary" style="margin-left:0;" href="{% url 'glimanagers:update' manager.pk %}">Editar administrador</a>

{% endblock tabcontent %}

ptgli/glimanagers/templates/glimanagers/list.html
{% extends 'glimanagers/base.html' %}
{% load static %}
{% load custom_tags %}
{% block tabcontent %}

<header class="gli-header">
    <div class="gli-breadcrumbs valign-wrapper">
        <a href="#" class="gli-breadcrumb">Inicio</a> <i class="gli-breadcrumb-active material-icons">keyboard_arrow_right</i> <span class="gli-breadcrumb-active">Administradores</span>
    </div>
    <h1 class="head">Administrador de la consola</h1>
</header>

<div class="gli-controls">
    <div class="gli-searchbar">
        <div>
            <i class="material-icons">search</i>
            <input type="text" id="search_by_manager" placeholder="Buscar" value="{{ search_filter }}">
            <button id='searchbutton' class="gli-button gli-button-tertiary">BUSCAR</button>
        </div>
        <div class="gli-filters-button">
            <button class="gli-button gli-button-secondary filters_button" style="padding: 10px;"><img style="margin: 0; padding: 0;" width="24" height="22" src="{% static 'glimanagers/img/filtericon.png' %}" alt=""></button>
            <div id="filters_form" class="gli-filters">
                <header>
                    <h3>Filtros de búsqueda</h3>
                    <div><i class="material-icons filters_button" style="cursor: pointer;">close</i></div>
                </header>
                <div class="gli-hsep" style="margin-bottom: 20px;"></div>
                <div class="gli-input gli-input-select">
                    <fieldset>
                        <legend>Área</legend>
                        <select id="areaselect">
                            <option  {% if area_filter == "" %}selected{% endif %} value="">Seleccionar</option>
                            {% for a in areaopt %}
                            <option {% if area_filter == a.0 %}selected{% endif %} value="{{ a.0 }}">{{ a.1 }}</option>
                            {% endfor %}
                                
                        </select>
                    </fieldset>
                </div>
                <div class="gli-input gli-input-select">
                    <fieldset>
                        <legend>Estatus</legend>
                        <select id="statusselect">
                            <option {% if status_filter == "" %}selected{% endif %} value="">Seleccionar</option>
                            {% for s in statusopt %}
                            <option {% if status_filter == s.0 %}selected{% endif %} value="{{ s.0 }}">{{ s.1 }}</option>
                            {% endfor %}
                        </select>
                    </fieldset>
                </div>
                <div class="gli-hsep" style="margin-bottom: 20px;"></div>
                <div class="buttons">
                    <a class="gli-button gli-button-white" style="background-color: #F5F5F5; border-width: 0;" href="{% url 'glimanagers:list' %}?rows={{ nrows }}">Limpiar</a>
                    <button id="applyfilters" class="gli-button gli-button-secondary">Aplicar filtros</button>
                </div>
            </div>
        </div>
    </div>
    
    <div>
        <button class="gli-button gli-button-white">Descargar</button>
        <a class="gli-button gli-button-secondary" href="{% url 'glimanagers:add' %}">Agregar nuevo admin</a>
    </div>
</div>


<div class="gli-mlist">
    <div class="gli-mlist-row gli-mlist-header">
        <div class="gli-mlist-column gli-select-column"><input type="checkbox" id="mlist_select_all"></div>
        <div class="gli-mlist-column gli-manager-column">Administradores</div>
        <div class="gli-mlist-column gli-area-column">Área</div>
        <div class="gli-mlist-column gli-email-column">Correo electrónico</div>
        <div class="gli-mlist-column gli-status-column">Estatus</div>
        <div class="gli-mlist-column gli-details-column">Detalles</div>
    </div>
    
    {% for manager in page_managers %}
    <div class="gli-mlist-row gli-mlist-item" id='manager_{{manager.pk}}'>
        <div class="gli-mlist-column gli-select-column"><input class="gli-select-checkbox" data-target='manager_{{manager.pk}}' type="checkbox"></div>
        <div class="gli-mlist-column gli-manager-column">
            {% if manager.display %}
            <div class="gli-manager-column-img">
                <img src="{% get_media_prefix %}{{ manager.display }}">
            </div>
            {% endif %}
            {{ manager.first_name }} {{ manager.last_name }}
        </div>
        <div class="gli-mlist-column gli-area-column">{{ manager.get_area_display }}</div>
        <div class="gli-mlist-column gli-email-column">{{ manager.email|safe_email }}</div>
        <div class="gli-mlist-column gli-status-column gli-status-column-{% if  manager.status == 1 %}active{% else %}inactive{% endif %}"><span>{{ manager.get_status_display }}</span></div>
        <div class="gli-mlist-column gli-details-column">
            <a href="{% url 'glimanagers:update' manager.pk %}"><img src="{% static 'glimanagers/img/edit.png' %}" alt="Editar" title="Editar"></a>
            <a href="#" class="delete-manager-button" data-target-pk="{{ manager.pk }}" data-target-name="{{ manager.first_name }} {{ manager.last_name }}" data-target-email='{{ manager.email|safe_email }}' data-target-img="{% if manager.display %}{% get_media_prefix %}{{ manager.display }}{% endif %}"><img src="{% static 'glimanagers/img/trash-2.png' %}" alt="Eliminar" title="Eliminar"></a>
            <a href="{% url 'glimanagers:details' manager.pk %}"><img src="{% static 'glimanagers/img/eye.png' %}" alt="Ver" title="Ver detalles"></a>
        </div>
    </div>
    {% endfor %}
</div>

<div class="gli-paginator">
    <span>Rows per page:</span>
    <select name="nrows" id="nrows">
        <option {% if nrows == 5 %}selected{% endif %} value="5">5</option>
        <option {% if nrows == 10 %}selected{% endif %} value="10">10</option>
        <option {% if nrows == 20 %}selected{% endif %} value="20">20</option>
        <option {% if nrows == 50 %}selected{% endif %} value="50">50</option>
    </select>
    <span>{{ niof }}-{{ nfof }} of {{ page_managers.paginator.count }}</span>
    {% if page_managers.has_previous %}
    <a href="{% url 'glimanagers:list' %}?page={{ page_managers.previous_page_number }}&search={{ search_filter }}&rows={{ nrows }}&area={{ area_filter }}&status={{ status_filter }}"><i class="material-icons">navigate_before</i></a>
    {% else %}
    <i class="material-icons" style="color: rgb(163, 163, 163);cursor: default;">navigate_before</i>
    {% endif %}
    {% if page_managers.has_next %}
    <a href="{% url 'glimanagers:list' %}?page={{ page_managers.next_page_number }}&search={{ search_filter }}&rows={{ nrows }}&area={{ area_filter }}&status={{ status_filter }}"><i class="material-icons">navigate_next</i></a>
    {% else %}
    <i class="material-icons" style="color: rgb(163, 163, 163);cursor: default;">navigate_next</i>
    {% endif %}
</div>

           
{% endblock tabcontent %}
{% block scripts %}
<script src="{% static 'glimanagers/gliscript.js' %}"></script>
{% endblock scripts %}

{% block modal %}
<div class="gli-modal">
    <div class="gli-modal-content">
        <a href="#" class="material-icons gli-modal-close gli-modal-close-cross">highlight_off</a>
        <h1 class="gli-modal-title">Eliminar administrador</h1>
        <div class="gli-hsep" style="width: 100%; margin-bottom: 24px;"></div>
        <p class="gli-normal-text" style="margin-bottom: 16px;">¿Estás seguro de eliminar a este administrador?</p>
        <div class="gli-modal-delete-confirm">
            <div class="gli-modal-delete-confirm-img">
                <img src="{% get_media_prefix %}{{ manager.display }}">
            </div>
            <div class="gli-modal-delete-confirm-data">
                <div class="gli-modal-delete-confirm-name">Nombre</div>
                <div class="gli-modal-delete-confirm-email">Correo @ correo</div>
            </div>
        </div>
        <div class="gli-hsep" style="width: 100%; margin-bottom: 24px;"></div>
        <div class="gli-modal-delete-buttons">
            <button class="gli-button gli-button-white gli-modal-close">Cancelar</button>
            <form action="{% url 'glimanagers:delete' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="-1" id="id_input_pk" name="pk">
                <button id="deletebutton" class="gli-button gli-button-secondary">Sí, eliminar</button>
            </form>
            
        </div>
    </div>
    
</div>
{% endblock modal %}
    

ptgli/glimanagers/templates/glimanagers/success.html
{% extends 'glimanagers/base.html' %}
{% load static %}
{% block tabcontent %}

<header class="gli-header">
    <div class="gli-breadcrumbs valign-wrapper">
        <a href="#" class="gli-breadcrumb">Inicio</a> <i class="gli-breadcrumb-active material-icons">keyboard_arrow_right</i> <span class="gli-breadcrumb-active">Administradores</span>
    </div>
    <h1 class="head">Administradores de la consola</h1>
</header>
<div class="gli-check">
    <span class="material-icons">done</span>
</div>
<h4 class="gli-normal-header">Cambios guardados</h4>
<p class="gli-normal-text">Tu administrador se ha guardado con éxito</p>
<a class="gli-button gli-button-secondary" style="margin-left:0; margin-top: 24px;" href="{% url 'glimanagers:list' %}">Regresar a mis administradores</a>

{% endblock tabcontent %}

ptgli/glimanagers/templates/glimanagers/update.html
{% extends 'glimanagers/base.html' %}
{% load static %}
{% block tabcontent %}

<header class="gli-header">
    <div class="gli-breadcrumbs valign-wrapper">
        <a href="#" class="gli-breadcrumb">Inicio</a> <i class="gli-breadcrumb-active material-icons">keyboard_arrow_right</i> <span class="gli-breadcrumb-active">Administradores</span>
    </div>
    <h1 class="head">Editar administrador</h1>
</header>
<p class="gli-normal-text" style="margin: 24px 0 16px 0;">Sube tu fotografía con un peso menor a 2MB</p>
<div class="add-form">
    <form id="addform" method="POST" enctype="multipart/form-data" style="width: 360px; margin-bottom: 40px;">
        {% csrf_token %}
        <div class="gli-img-dropable">
            <div class="gli-img-dropable-preview gli-img-dropable-{% if not manager.display %}no-{% endif %}preview">
                {% if manager.display %}
                <img src="{% get_media_prefix %}{{ form.instance.display }}" alt="">        
                {% else %}
                <img src="{% static 'glimanagers/img/nodisplay.png' %}" alt="">    
                {% endif %}                
            </div>
            <div class="gli-img-dropable-input">
                <small>Arrastra tu archivo o</small>
                <div class="gli-img-dropable-button-select">
                    <input type="file" name="display" accept="image/*" id="id_display">
                    <label for="{{form.display.id_for_label}}" class="gli-button gli-button-white">Selecciona</label>
                </div>
            </div>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Nombre (s) </legend>
                {{ form.first_name }}
            </fieldset>
            <small class="gli-form-error">{{ form.first_name.errors }}</small>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Apeliidos </legend>
                {{ form.last_name }}
            </fieldset>
            <small class="gli-form-error">{{ form.last_name.errors }}</small>
        </div>
        <div class="gli-input gli-input-text">
            <fieldset>
                <legend>Correo electrónico </legend>
                {{ form.email }}
            </fieldset>
            <small class="gli-form-error">{{ form.email.errors }}</small>
        </div>
        <div class="gli-input gli-input-select">
            <fieldset>
                <legend>Área</legend>
                {{ form.area }}
            </fieldset>
        </div>
        <div class="gli-input gli-input-select">
            <fieldset>
                <legend>Estatus</legend>
                {{ form.status }}
            </fieldset>
        </div>
    </form>
</div>

<div class="gli-hsep" style="margin-bottom: 16px;"></div>
<div>
    <a class="gli-button gli-button-white" href="{% url 'glimanagers:list' %}">Cancelar</a>
    <button id="addbutton" class="gli-button gli-button-secondary">Guardar cambios</button>
</div>
{% endblock tabcontent %}
{% block scripts %}
<script src="{% static 'glimanagers/glimanagerform.js' %}"></script>
{% endblock scripts %}
    